title: "Spirit Connect â€“ Power Labs"
description: "AI-Assisted Power Electronics Converter Design Automation"
url: https://fulongli.github.io
baseurl: "/spiritconnectsciandtec.github.io"
timezone: Europe/London
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
