title: "Spirit Connect Science and Technology"
description: "Copy and update human consciousness and memory to the digital world"
url: https://fulongli.github.io
baseurl: "/spiritconnectsciandtec.github.io"
timezone: Europe/London
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
